export declare function generateDeviceFingerprint(): string;
export declare function signProof(data: Record<string, any>): string;
export declare function socialRegister(nickname: string, totalTokens: number, level: number, uptimeHours: number): Promise<any>;
export declare function socialLogin(): Promise<any>;
export declare function socialSync(token: string, totalTokens: number, level: number, achievements: number, dailyTokens: number): Promise<any>;
export declare function socialGetLeaderboard(token: string | null, type: string, page: number): Promise<any>;
export declare function socialCreatePK(token: string): Promise<any>;
export declare function socialJoinPK(token: string, pkCode: string): Promise<any>;
export declare function socialGetProfile(token: string): Promise<any>;
export declare function socialUpdateProfile(token: string, data: Record<string, any>): Promise<any>;
export declare function socialDeleteAccount(token: string): Promise<any>;
export declare function socialGetStats(): Promise<any>;
